# Generated by Django 5.2 on 2025-04-16 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0002_image_product_alter_image_image_delete_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dropshipping.products'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
