# Generated by Django 5.2 on 2025-04-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0005_alter_image_id_alter_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
