# Generated by Django 5.2 on 2025-04-19 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0006_products_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(max_length=15, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='Phone number must be between 7 and 15 digits.', regex='^\\d{7,15}$')]),
        ),
    ]
