# Generated by Django 5.2 on 2025-04-19 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0007_alter_users_password_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.RegexValidator(message='Phone number must be between 7 and 15 digits.', regex='^\\d{7,15}$')]),
        ),
    ]
