# Generated by Django 5.2 on 2025-04-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropshipping', '0010_alter_orderdetail_product_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
